# name: Test ARC Runner

# on:
#   workflow_dispatch:

# jobs:
#   test:
#     runs-on: [self-hosted, arc, aks, dind]
#     steps:
#       - name: Hello from ARC runner
#         run: |
#           echo "Runner hostname: $(hostname)"
#           docker version
# name: Actions Runner Controller Demo
# on:
#   workflow_dispatch:

# jobs:
#   Explore-GitHub-Actions:
#     # You need to use the INSTALLATION_NAME from the previous step
#     runs-on: ubuntu-20-04-16g
#     steps:
#     - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
# name: ARC Test
# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-20-04-16g
#     steps:
#       - run: |
#           echo "Runner hostname: $(hostname)"
#           docker --version || echo "Docker not installed yet"

name: ARC Docker Test

on: [push]

jobs:
  docker-test:
    runs-on: ubuntu-20-04-16g   # ðŸ‘ˆ same runnerScaleSetName

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker info
          
      - name: Build test image
        run: |
          docker build -t arc-docker-test .

      - name: Run test container
        run: |
          docker run --rm arc-docker-test


