name: ARC Test

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: [self-hosted, aks-arc-dind]
    steps:
      - run: echo "Runner picked"
      - run: python --version
      - run: docker version

